name: Test workflow

on:
    pull_request:
        branches: 
            - develop

jobs: 
    test: 
        runs-on: ubuntu-latest

        steps: 
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Use Node.js 20.x
              uses: actions/setup-node@v1
              with: 
                node-version: 20.x
            
            - name: Install Dependencies
              run: npm install

            - name: Run Build
              run: npm run build

            - name: Run Start
              run: npm run start
            # should probably remove this from here because the tests are ran when a PR is made to to develop, and only develop can merge with main.
            - name: Run Tests
              run: npm run test